name: Checking current directory Path

on:
    workflow_dispatch:

env: 
    AZURE_FUNCTIONAPP_PACKAGE_PATH: /

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: checkout explore
              uses: actions/checkout@v4
              with:
                  path: /
              
            - name: listing
              shell: bash
              run: ls
            
            - name: listing long
              shell: bash
              run: ls -l
            
            - name: listing all
              shell: bash
              run: ls -a
            
            - name: pwd
              run: pwd
            - name: List files
              run: ls -la /home/runner/work/prac/prac

            - name: 'Resolve Project Dependencies Using Npm'
              shell: bash
              run: |
                pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
                ls -la
                npm install
                npm run build --if-present
                npm run test --if-present
                popd